package com.system.bibliotec.service.vo;

public enum TipoTrabalhoEnum {

    NOTIFICACAO_EM_LOTE, PROCESSAMENTO_MIGRACAO,
    PROCESSO_GENERICO, CONFERENCIA_LOCACOES_VENCIDAS,
    CONFERENCIA_RESERVAS_VENCIDAS;
}
